In [104]:
#加载停用词
with open('chinese_stopwords.txt', 'r', encoding='utf-8') as file:
    stopword = [i[:-1] for i in file.readlines()]
print(stopword)

['，', '的', '。', '、', '在', '了', '是', '\u3000', '“', '”', '和', '年', '月', '：', '也', '）', '为', '（', '有', '%', '日', '将', '中', '-', '到', '与', '对', ':', '\xa0', '上', '都', '等', '不', '他', '》', '《', '就', '但', '我', '而', '这', '会', '并', '；', '被', '后', '人', '从', '还', '1', '3', '6', '以', '新', '说', '7', '2', '要', '5', '？', '更', '于', '个', '10', '大', '时', '4', '多', '/', '让', '其', ')', '(', '很', '及', '下', '', '能', '—', '或', '该', '她', '比', '8', '元', '12', '已', '向', '做', '来', '前', '由', '好', '.', '称', '给', '最', '11', '·', '据', '着', '又', '至', '9', '20', '！', '[', ']', '去', '可', '把', '则', '', '一', '地', '高', '吗', '30', '所', '分', '较', '内', '第', '里', '占', '过', '15', '曾', '"', '再', '人民日报', '新闻网', '它', '况', '而且', '而是', '而外', '而言', '而已', '尔后', '反过来', '反过来说', '反之', '非但', '非徒', '否则', '嘎', '嘎登', '该', '赶', '个', '各', '各个', '各位', '各种', '各自', '给', '根据', '跟', '故', '故此', '固然', '关于', '管', '归', '果然', '果真', '过', '哈', '哈哈', '呵', '和', '何', '何处', '何况', '何时', '嘿', '哼', '哼唷', '呼哧', '乎', '哗', '还是', '还有', '换句话说', '换言之', '或', '或是', '或

In [105]:
#数据加载
import pandas as pd
news = pd.read_csv('sqlResult.csv', encoding='gb18030')
news.head()

id      author                  source  \
0  89617         NaN  快科技@http://www.kkj.cn/   
1  89616         NaN  快科技@http://www.kkj.cn/   
2  89615         NaN  快科技@http://www.kkj.cn/   
3  89614         NaN                     新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  
0     http://www.cnbeta.com/articles/tech/623597.htm  
1     http://www.cnbeta.com/articles/tech/623599.htm  
2     http://www.cnbeta.com/articles/tech/623601.htm  
3  http://world.huanqiu.com/hot/2017-06/10866126....  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...

In [106]:
news.shape

(89611, 7)

In [107]:
#处理缺失值
news=news.dropna(subset=['content'])

In [108]:
news.shape

(87054, 7)

In [6]:
#分词
import jieba
def split_text(text):
    text = text.replace(' ','').replace('\n','')
    text2 = jieba.cut(text.strip())
    #去掉停用词
    result = ' '.join([w for w in text2 if w not in stopword])
    return result
print(news.iloc[0])

id                                                     89617
author                                                   NaN
source                                快科技@http://www.kkj.cn/
content    此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...
feature    {"type":"科技","site":"cnbeta","commentNum":"37"...
title                                   小米MIUI 9首批机型曝光：共计15款
url           http://www.cnbeta.com/articles/tech/623597.htm
Name: 0, dtype: object


In [7]:
print(news.iloc[0].content)

此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/体验版内测，稳定版暂不受影响），以确保工程师可以集中全部精力进行系统优化工作。有人猜测这也是将精力主要用到MIUI 9的研发之中。
MIUI 8去年5月发布，距今已有一年有余，也是时候更新换代了。
当然，关于MIUI 9的确切信息，我们还是等待官方消息。



In [8]:
print(split_text(news.iloc[0].content))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\huyid\AppData\Local\Temp\jieba.cache
Loading model cost 0.665 seconds.
Prefix dict has been built successfully.


 当然 MIUI9 确切 信息 等待 官方消息


In [9]:
#对所有文本进行分词
corpus = list(map(split_text, [str(i) for i in news.content]))

In [10]:
print(corpus[0])

 当然 MIUI9 确切 信息 等待 官方消息


In [11]:
print(corpus[0:2])

['此外 本周 除 小米 手机 款 机型 外 机型 暂停 更新 发布 含 开发 版 体验版 内测 稳定版 暂不受 影响 确保 工程师 集中 全部 精力 进行 系统优化 工作 有人 猜测 精力 主要 用到 MIUI9 研发 之中 \r MIUI8 去年 发布 距今已有 一年 有余 更新换代 \r 当然 MIUI9 确切 信息 等待 官方消息', '骁龙 835 唯一 Windows10 桌面 平台 认证 ARM 处理器 高通 强调 不会 只 考虑 性能 屏蔽掉 小 核心 相反 正 联手 微软 找到 一种 适合 桌面 平台 兼顾 性能 功耗 完美 方案 \r 报道 微软 已经 拿到 一些 源码 Windows10 更好 理解 big little 架构 \r 资料 显示 骁龙 835 一款 集成 CPU GPU 基带 蓝牙 Wi Fi SoC 传统 Wintel 方案 节省 至少 30% PCB 空间 \r 按计划 今年 Q4 华硕 惠普 联想 首发 骁龙 835Win10 电脑 预计 均 二合一 形态 产品 \r 当然 高通 骁龙 未来 也许 见到 三星 Exynos 联发科 华为 麒麟 小米 澎湃 进入 Windows10 桌面 平台']


In [12]:
print(len(corpus))

87054


In [13]:
import pickle, os
if not os.path.exists('corpus.pkl'):
    #把corpus保存到文件file中去，方便下次使用
    with open('corpus.pkl','wb') as file: 
        pickle.dump(corpus, file)
else:
    #调用上次处理的结果
    with open('corpus.pkl', 'rb') as file:
        corpus = pickle.load(file)
        
#计算corpus中的TFIDF矩阵
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
countvectorizer = CountVectorizer(encoding='gb18030', min_df=0.015)
tfidftransformer = TfidfTransformer()
#先做TF，再做IDF =>TFIDF
countvector=countvectorizer.fit_transform(corpus) #fit是学习数据中的参数，transform是根据学到的参数，进行预处理，得到想要的结果
print(countvector) #np.array的简化写法。第0行第174列的词出现了一次。
print(countvector.toarray()) #corpus每句话是一行，第174列的词在第0行这句话中出现了一次。
print(countvector.toarray()[0,174])

  (0, 174)	1
  (0, 44)	1
  (0, 263)	1
  (0, 667)	1
  (0, 103)	1
  (0, 385)	1
  (0, 822)	1
  (0, 184)	1
  (0, 860)	1
  (0, 669)	1
  (0, 432)	1
  (0, 416)	1
  (0, 271)	2
  (0, 461)	1
  (0, 590)	1
  (1, 820)	1
  (1, 562)	1
  (1, 123)	1
  (1, 873)	1
  (1, 137)	1
  (1, 679)	1
  (1, 734)	1
  (1, 155)	1
  (1, 544)	1
  (1, 788)	1
  :	:
  (87053, 76)	2
  (87053, 434)	2
  (87053, 108)	2
  (87053, 793)	1
  (87053, 34)	7
  (87053, 628)	2
  (87053, 574)	1
  (87053, 815)	1
  (87053, 335)	3
  (87053, 157)	1
  (87053, 120)	1
  (87053, 856)	1
  (87053, 586)	1
  (87053, 37)	1
  (87053, 52)	1
  (87053, 561)	1
  (87053, 770)	2
  (87053, 520)	2
  (87053, 410)	1
  (87053, 734)	1
  (87053, 35)	1
  (87053, 391)	1
  (87053, 263)	2
  (87053, 385)	2
  (87053, 461)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 6 0]]
1


In [14]:
tfidf = tfidftransformer.fit_transform(countvector)
print(tfidf)

  (0, 860)	0.26741301446611326
  (0, 822)	0.15081854599522596
  (0, 669)	0.26715029976903004
  (0, 667)	0.28310913637357893
  (0, 590)	0.2377366084883309
  (0, 461)	0.2878070027067415
  (0, 432)	0.21738727660389703
  (0, 416)	0.2635695091361039
  (0, 385)	0.1850186934955745
  (0, 271)	0.4315600570411225
  (0, 263)	0.22919853031116053
  (0, 184)	0.24678558372830625
  (0, 174)	0.23457323800243957
  (0, 103)	0.20107856367304278
  (0, 44)	0.2622556328284512
  (1, 873)	0.17465909584945621
  (1, 820)	0.14309912032193292
  (1, 788)	0.20691439678871912
  (1, 734)	0.19373288221007326
  (1, 721)	0.1952386254577293
  (1, 679)	0.188737398870923
  (1, 579)	0.18803588094997306
  (1, 562)	0.15539264680070092
  (1, 548)	0.18677188359667968
  (1, 544)	0.15252789064897018
  :	:
  (87053, 225)	0.051599157024469496
  (87053, 216)	0.12471943940235379
  (87053, 211)	0.053105578732374634
  (87053, 208)	0.09807841154338856
  (87053, 171)	0.05426534900359052
  (87053, 157)	0.05461867428919075
  (87053, 151)	0.

In [15]:
type(tfidf)

scipy.sparse.csr.csr_matrix

In [16]:
#标记是否为自己的新闻
label = list(map(lambda source:1 if '新华' in str(source) else 0,news.source))
print(label)

[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 

In [17]:
#数据切分
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tfidf.toarray(), label, test_size=0.3) # Allowed inputs are lists, numpy arrays, scipy-sparse matrices or pandas dataframes.

In [18]:
from sklearn.naive_bayes import MultinomialNB 
clf = MultinomialNB()
clf.fit(X_train, y_train)
y_predict = clf.predict(X_test)
print(y_predict)

[0 1 1 ... 0 1 1]


In [19]:
#使用模型检测抄袭新闻，预测风格 （看预测的label是否为新华社）
#predition代表 风格预测， prediction=1 代表风格预测为新华社
#labels代表实际值，如果label=1 说明实际为新华社
prediction = clf.predict(tfidf.toarray())

In [20]:
import numpy as np
labels = np.array(label) #实际的labels

In [21]:
#compare_news_index有两列，prediction为预测风格，labels为实际
compare_news_index = pd.DataFrame({'prediction': prediction, 'labels': labels})
print(compare_news_index)

       prediction  labels
0               0       0
1               0       0
2               0       0
3               1       1
4               1       0
5               0       0
6               0       0
7               0       0
8               0       0
9               0       0
10              0       0
11              0       0
12              0       0
13              0       0
14              0       0
15              0       0
16              0       0
17              0       1
18              0       0
19              0       0
20              0       0
21              0       0
22              0       0
23              0       0
24              1       0
25              1       1
26              0       0
27              0       1
28              1       0
29              0       0
...           ...     ...
87024           1       1
87025           1       1
87026           1       1
87027           1       1
87028           1       1
87029           1       1
87030       

In [22]:
#有嫌疑的index：预测为新华社风格，但label又不是新华社
copy_news_index = compare_news_index[(compare_news_index['prediction'] == 1) & (compare_news_index['labels'] == 0)]
print(copy_news_index)

      prediction  labels
4              1       0
24             1       0
28             1       0
30             1       0
35             1       0
37             1       0
38             1       0
43             1       0
45             1       0
49             1       0
50             1       0
57             1       0
59             1       0
63             1       0
66             1       0
69             1       0
71             1       0
75             1       0
79             1       0
81             1       0
82             1       0
87             1       0
88             1       0
93             1       0
96             1       0
99             1       0
103            1       0
105            1       0
107            1       0
109            1       0
...          ...     ...
8491           1       0
8492           1       0
8494           1       0
8501           1       0
8502           1       0
8504           1       0
8506           1       0
8508           1       0


In [80]:
print(copy_news_index.index)

Int64Index([   4,   24,   28,   30,   35,   37,   38,   43,   45,   49,
            ...
            8535, 8538, 8539, 8543, 8544, 8546, 8548, 8549, 8551, 8552],
           dtype='int64', length=2790)


In [84]:
#有嫌疑的文章的index
potentialindex=copy_news_index.index

In [23]:
#实际为新华社的新闻
xinhuashe_news_index = compare_news_index[(compare_news_index['labels'] == 1)].index
print(xinhuashe_news_index)

Int64Index([    3,    17,    25,    27,    39,    51,    65,    95,   102,
              111,
            ...
            87044, 87045, 87046, 87047, 87048, 87049, 87050, 87051, 87052,
            87053],
           dtype='int64', length=78855)


In [24]:
print('可能为copy的新闻条数', len(copy_news_index))

可能为copy的新闻条数 2790


In [25]:
#使用kmeans对文章进行聚类
from sklearn.preprocessing import Normalizer
from sklearn.cluster import KMeans
normalizer = Normalizer()
scaled_array = normalizer.fit_transform(tfidf.toarray())

In [26]:
# 25是人工定义的桶的个数，聚类的个数
kmeans = KMeans(n_clusters=25)
k_labels = kmeans.fit_predict(scaled_array)

In [27]:
print(k_labels)

[ 0 17 17 ...  8 17 17]


In [46]:
len(k_labels)

87054

In [45]:
np.unique(k_labels)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
# 创建id_class
id_class = {index:class_ for index, class_ in enumerate(k_labels)}
print(id_class)

{0: 0, 1: 17, 2: 17, 3: 12, 4: 17, 5: 19, 6: 17, 7: 19, 8: 17, 9: 19, 10: 19, 11: 19, 12: 17, 13: 19, 14: 19, 15: 19, 16: 0, 17: 17, 18: 19, 19: 19, 20: 8, 21: 19, 22: 17, 23: 19, 24: 17, 25: 0, 26: 17, 27: 17, 28: 17, 29: 19, 30: 0, 31: 17, 32: 0, 33: 17, 34: 17, 35: 17, 36: 17, 37: 17, 38: 17, 39: 12, 40: 17, 41: 0, 42: 5, 43: 17, 44: 17, 45: 15, 46: 19, 47: 19, 48: 17, 49: 17, 50: 17, 51: 9, 52: 17, 53: 0, 54: 17, 55: 0, 56: 17, 57: 5, 58: 0, 59: 0, 60: 0, 61: 17, 62: 5, 63: 24, 64: 15, 65: 17, 66: 15, 67: 5, 68: 5, 69: 17, 70: 17, 71: 15, 72: 0, 73: 0, 74: 0, 75: 17, 76: 17, 77: 17, 78: 0, 79: 17, 80: 17, 81: 17, 82: 17, 83: 17, 84: 17, 85: 0, 86: 0, 87: 17, 88: 19, 89: 5, 90: 5, 91: 17, 92: 0, 93: 8, 94: 5, 95: 5, 96: 15, 97: 17, 98: 5, 99: 0, 100: 19, 101: 0, 102: 17, 103: 17, 104: 17, 105: 0, 106: 5, 107: 17, 108: 0, 109: 5, 110: 19, 111: 0, 112: 0, 113: 5, 114: 17, 115: 19, 116: 5, 117: 5, 118: 0, 119: 0, 120: 17, 121: 18, 122: 17, 123: 21, 124: 17, 125: 18, 126: 17, 127: 17, 1

In [29]:
from collections import defaultdict
class_id = defaultdict(set)
for index, class_ in id_class.items(): #Python Dictionary items() Method returns key-value pairs of the dictionary, as tuples in a list.
    # 只统计新华社发布的class_id
    if index in xinhuashe_news_index.tolist():
        class_id[class_].add(index)

In [30]:
print(class_id)

defaultdict(<class 'set'>, {12: {3, 39, 57446, 82047, 24723, 24724, 24725, 24729, 24731, 24735, 24737, 24738, 24739, 41149, 41154, 16581, 34232, 16585, 41162, 32974, 32975, 32976, 32977, 32978, 32979, 32980, 16594, 32982, 32983, 32984, 16595, 32986, 16596, 16597, 16598, 16599, 16600, 32985, 41181, 41184, 41185, 41187, 41182, 41183, 16625, 16626, 16627, 16629, 24829, 24831, 24833, 24835, 41231, 16661, 41238, 41239, 16664, 41240, 33050, 41241, 41242, 33053, 33054, 41243, 33057, 16676, 16678, 16689, 16703, 57672, 57673, 57674, 57675, 24908, 16722, 16723, 16724, 16725, 16729, 16730, 16731, 16732, 16733, 16734, 16735, 33119, 16737, 33122, 33124, 24934, 33152, 33153, 33154, 33155, 8580, 8581, 8582, 8583, 8584, 8585, 8586, 8587, 8588, 8589, 24965, 33158, 33159, 33160, 33161, 33163, 33164, 33165, 33166, 33167, 33168, 33169, 33170, 33171, 33172, 24992, 24993, 24994, 24995, 24996, 24997, 24999, 25000, 25002, 25005, 25010, 25011, 25015, 33208, 25048, 25064, 41477, 49672, 49673, 25100, 25101, 4968

In [31]:
print(class_id.keys())

dict_keys([12, 17, 0, 9, 5, 6, 15, 8, 19, 18, 24, 14, 13, 7, 1, 20, 23, 16, 22, 10, 2, 21, 11, 4, 3])


In [47]:
# 查找相似文本
from sklearn.metrics.pairwise import cosine_similarity
def find_similar_text(cpindex, top=10):
    #只在新华社发布的文章中查找
    dist_dict = {i:cosine_similarity(tfidf[cpindex], tfidf[i]) for i in class_id[id_class[cpindex]]}
    #从大到小进行排序
    return sorted(dist_dict.items(), key=lambda x:x[1][0], reverse=True)[:top]

In [86]:
# 测试有嫌疑的文章与哪些新华社的文章相似
cpindex=potentialindex[2]
print(cpindex)
similar_list = find_similar_text(cpindex)
print(similar_list)

28
[(54858, array([[0.4790132]])), (54976, array([[0.47379451]])), (18495, array([[0.46644004]])), (75084, array([[0.46600637]])), (82080, array([[0.45851198]])), (52291, array([[0.45596554]])), (76849, array([[0.45554416]])), (86111, array([[0.43596508]])), (24206, array([[0.43159321]])), (86001, array([[0.42976636]]))]


In [88]:
print('怀疑抄袭来的文章:\n', news.iloc[cpindex].content)

怀疑抄袭来的文章:
 中超联赛第13轮比赛已经全部结束，这轮比赛中最让人觉得结果有些出乎意料的，莫过于卡佩罗执教江苏苏宁的主场首秀却以失败告终，在其他球队换帅如换刀的背景下，苏宁却持续陷入低迷，13轮过后只积8分，排名倒数第2，近3年1铁律预示苏宁想保级除非创造奇迹。
就在去年也就是2016赛季，由于中超第21轮被提前，因此中超第21轮比赛结束后也就相当于如今的13轮比赛过后，当时杭州绿城只积9分，山东鲁能由于少赛一场，也积9分，同处降级区，但是鲁能在第13场比赛战平上港，因此13场过后积分应为10分，最终杭州绿城降级，鲁能惊险保级。
再往前推，2015赛季，中超13轮比赛过后，贵州人和与上海申鑫排在倒数第1和第2位，贵州人和积10分，而上海申鑫只有4分，最终这2支球队全部降级，也就是说当时第13轮比赛的降级区球队成为了最终联赛结束后真正降级的2支球队。
然后回到2014赛季，前13轮比赛过后，身处降级区的是哈尔滨毅腾和河南建业两支球队，河南建业已经有10分入账，而哈尔滨毅腾在少赛一场的情况下只积5分，即使算上哈尔滨毅腾第13场比赛能赢，最多也是8分，最终哈尔滨毅腾降级。
从这3年的中超13轮比赛过后的积分榜来看，会发现一个铁律，那就是所有在13轮比赛结束后，还低于10分的球队，最终全部降级，无一幸免。如今江苏苏宁在13轮过后竟然只获得了1场胜利，积分只有8分，接下来的比赛除非创造奇迹打破这三年来的铁律，才可能保级，苏宁从现在开始真的是为保级而战了！（老邱中超球评）



In [89]:
#找一篇相似的原文
similarexample = similar_list[0][0]
similarexample

54858

In [90]:
print('原文可能是：\n', news.iloc[similarexample].content)

原文可能是：
 　　新华社南京５月１０日电　亚冠小组赛综述：中超创造历史\n　　新华社记者　王恒志\n　　２０１７赛季亚冠小组赛１０日尘埃落定，中超球队在这个赛季的小组赛中表现出色，历史上首次有三支球队杀进亚冠１６强，同时江苏苏宁队创造提前两轮出线和小组赛积分最高（１５分）历史、广州恒大队则成为首支小组赛不败的中超球队。而淘汰赛尚未开打，另一项历史已经出现：苏宁将和上海上港队送出亚冠赛场上的首次“中国德比”。\n　　拥有众多大牌外教和外援的中超这个赛季在亚冠赛场上可谓威风八面，江苏苏宁队和上海上港队都早早提前锁定小组出线名额，苏宁更是创纪录地以四连胜提前两轮锁定小组头名。不过，从比赛内容来说，上港的场上表现毫无疑问更为出色，奥斯卡、胡尔克等球员的火热状态让他们一路高歌猛进，苏宁虽然连战连捷，但人员不整的他们在有些场次场面上处于下风，只是凭借拉米雷斯和特谢拉的“灵光一闪”才一路高奏凯歌。\n　　不过，苏宁在最后一轮仍然在创造历史，以全华班出战的他们客场１:０小胜澳大利亚的阿德莱德联队，１５分的积分创造了２００９年亚冠改制后中超球队小组赛最高纪录，中超球队全华班取胜也是头一遭。这个赛季的苏宁堪称“亚冠球队”，尽管联赛八轮不胜，但在亚冠赛场他们队史首次出线，同时还缔造了一系列中超纪录。\n　　令人稍显意外的是广州恒大，他们直到最后一轮还要确保不输球才能晋级。好在恒大底蕴犹在，最终以小组第二的身份出线。但同时，恒大仍然创造了历史，２平４负的不败战绩让他们成为改制后首支小组赛不败的中超球队。\n　　更重要的是，这是首次有三支中超球队打进亚冠１６强，此前中超的最好战绩是两支球队出线，本赛季上海申花队在资格赛落败，只有三支球队参加小组赛，结果他们全部晋级，给了中国球迷一个大惊喜。\n　　与之相对的是，本赛季澳大利亚和韩国球队呈“溃败”之势，澳超全军覆没，韩国Ｋ联赛也仅存济州联队一支“独苗”。不过，日本球队表现更为强势，他们四支球队出战三支出线，而且浦和红钻、鹿岛鹿角和川崎前锋三队均是以小组头名晋级。此外泰国的蒙通联队获得一张东亚区１６强席位。\n　　令很多中国球迷惋惜的是，虽然有三支中超球队晋级，但１６强战就将上演“中国德比”。上港在１０日的小组赛最后一轮２:３落败，在浦和红钻输球的情况下，没能反超对手登上积分榜首，获得小组第二的他们将在淘汰赛阶段迎战江苏苏宁队。虽然早早同室操戈